name: Publish Hub - kafka-source

permissions: read-all

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to checkout"
        type: string
        default: "main"

jobs:
  publish:
    uses: infinyon/fluvio/.github/workflows/connector-publish.yml@master
    with:
      package-name: kafka-source
      branch: ${{ github.event.inputs.branch }}
      readme: "./crates/kafka-source/README.md"
      fail-fast: false
    secrets:
      CLOUD_USER_EMAIL: ${{ secrets.ORG_CLOUD_SERVICE_EMAIL }}
      CLOUD_USER_PASSWORD: ${{ secrets.ORG_CLOUD_SERVICE_PASSWD_PROD }}
